apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: configuration
spec:
  rules:
  - host: configuration.192.168.0.9.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: configuration
          servicePort: 32000
---
kind: Service
apiVersion: v1
metadata:
  name: configuration
spec:
  type: NodePort
  selector:
    app: spring-cloud-config
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 32000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-config
  labels:
    app: spring-cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-config
  template:
    metadata:
      labels:
        app: spring-cloud-config
        version: latest
    spec:
      hostname: configuration
      subdomain: configuration
      containers:
      - name: spring-cloud-config
        image: 192.168.0.8:5000/configuration-server:latest
        ports:
        - name: http
          containerPort: 8888